import type { ImageSourcePropType } from 'react-native';

/** Local asset keys → bundled images for Dust & Iron / Vulture Gang media pack. */
export const DUST_AND_IRON_MEDIA_ASSETS: Record<string, ImageSourcePropType> = {
  'dust-and-iron.mood': require('@/assets/images/narrative/dust-and-iron/mood/dust-and-iron-mood.webp.png'),
  'dust-and-iron.saga.vulture-gang-banner': require('@/assets/images/narrative/dust-and-iron/sagas/vulture-gang-banner.webp.png'),
  'dust-and-iron.saga.iron-railway-company-banner': require('@/assets/images/narrative/dust-and-iron/sagas/iron-railway-company-banner.png.png'),
  'dust-and-iron.saga.iron-railway-office': require('@/assets/images/narrative/dust-and-iron/chapters/iron-railway/iron-railway-office.png.png'),
  'dust-and-iron.character.ada-mercer-neutral': require('@/assets/images/narrative/dust-and-iron/characters/ada-mercer-neutral.webp.png'),
  'dust-and-iron.character.ada-mercer-approving': require('@/assets/images/narrative/dust-and-iron/characters/ada-mercer-approving.png.png'),
  'dust-and-iron.character.ada-mercer-worried': require('@/assets/images/narrative/dust-and-iron/characters/ada-mercer-worried.png.png'),
  'dust-and-iron.character.elias-crow-neutral': require('@/assets/images/narrative/dust-and-iron/characters/elias-crow-neutral.png.png'),
  'dust-and-iron.character.elias-crow-taunting': require('@/assets/images/narrative/dust-and-iron/characters/elias-crow-taunting.webp.png'),
  'dust-and-iron.character.elias-crow-angry': require('@/assets/images/narrative/dust-and-iron/characters/elias-crow-angry.png.png'),
  'dust-and-iron.character.station-master-briggs-neutral': require('@/assets/images/narrative/dust-and-iron/characters/station-master-briggs-neutral.webp.png'),
  'dust-and-iron.character.station-master-briggs-approving': require('@/assets/images/narrative/dust-and-iron/characters/station-master-briggs-approving.png.png'),
  'dust-and-iron.character.station-master-briggs-concerned': require('@/assets/images/narrative/dust-and-iron/characters/station-master-briggs-concerned.png.png'),
  'dust-and-iron.character.station-master-briggs-railway': require('@/assets/images/narrative/dust-and-iron/characters/station-master-briggs-railway.png.png'),
  'dust-and-iron.character.silas-vane-neutral': require('@/assets/images/narrative/dust-and-iron/characters/iron-railway-antagonist-neutral.png.png'),
  'dust-and-iron.character.silas-vane-angry': require('@/assets/images/narrative/dust-and-iron/characters/iron-railway-antagonist-angry.png.png'),
  'dust-and-iron.chapter.01-dustfall-gate': require('@/assets/images/narrative/dust-and-iron/chapters/01-dustfall-gate.webp.png'),
  'dust-and-iron.chapter.02-burnt-warehouse': require('@/assets/images/narrative/dust-and-iron/chapters/02-burnt-warehouse.webp.png'),
  'dust-and-iron.chapter.03-broken-wagon-trail': require('@/assets/images/narrative/dust-and-iron/chapters/03-broken-wagon-trail.webp.png'),
  'dust-and-iron.chapter.04-ambush-canyon': require('@/assets/images/narrative/dust-and-iron/chapters/04-ambush-canyon.webp.png'),
  'dust-and-iron.chapter.05-high-noon-square': require('@/assets/images/narrative/dust-and-iron/chapters/05-high-noon-square.webp.png'),
  'dust-and-iron.chapter.iron-railway.01-railyard-gate': require('@/assets/images/narrative/dust-and-iron/chapters/iron-railway/01-railyard-gate.png.png'),
  'dust-and-iron.chapter.iron-railway.02-cargo-hold-six': require('@/assets/images/narrative/dust-and-iron/chapters/iron-railway/02-cargo-hold-six.png.png'),
  'dust-and-iron.chapter.iron-railway.03-broken-tracks-pass': require('@/assets/images/narrative/dust-and-iron/chapters/iron-railway/03-broken-tracks-pass.png.png'),
  'dust-and-iron.chapter.iron-railway.04-freight-war-junction': require('@/assets/images/narrative/dust-and-iron/chapters/iron-railway/04-freight-war-junction.png.png'),
  'dust-and-iron.chapter.iron-railway.05-golden-route-terminal': require('@/assets/images/narrative/dust-and-iron/chapters/iron-railway/05-golden-route-terminal.png.png'),
  'dust-and-iron.reward.first-dustfall-patrol': require('@/assets/images/narrative/dust-and-iron/ui/reward-first-dustfall-patrol.png.png'),
  'dust-and-iron.reward.smoke-watcher': require('@/assets/images/narrative/dust-and-iron/ui/reward-smoke-watcher.png.png'),
  'dust-and-iron.reward.railway-bandana': require('@/assets/images/narrative/dust-and-iron/ui/reward-railway-bandana.png.png'),
  'dust-and-iron.reward.ambush-survivor': require('@/assets/images/narrative/dust-and-iron/ui/reward-ambush-survivor.png.png'),
  'dust-and-iron.reward.iron-railway-unlock': require('@/assets/images/narrative/dust-and-iron/ui/reward-iron-railway-unlock.png.png'),
  'dust-and-iron.reward.iron-railway.railyard-access-pass': require('@/assets/images/narrative/dust-and-iron/ui/iron-railway/reward-railyard-access-pass.png.png'),
  'dust-and-iron.reward.iron-railway.cargo-ledger-seal': require('@/assets/images/narrative/dust-and-iron/ui/iron-railway/reward-cargo-ledger-seal.png.png'),
  'dust-and-iron.reward.iron-railway.track-repair-kit': require('@/assets/images/narrative/dust-and-iron/ui/iron-railway/reward-track-repair-kit.png.png'),
  'dust-and-iron.reward.iron-railway.route-marshal-badge': require('@/assets/images/narrative/dust-and-iron/ui/iron-railway/reward-route-marshal-badge.png.png'),
  'dust-and-iron.reward.iron-railway.golden-route-charter': require('@/assets/images/narrative/dust-and-iron/ui/iron-railway/reward-golden-route-charter.png.png'),
};
