import type { ImageSourcePropType } from 'react-native';

/** Local asset keys → bundled images for NeuroNet narrative media packs. */
export const NEURONET_MEDIA_ASSETS: Record<string, ImageSourcePropType> = {
  'neuronet.mood': require('@/assets/images/narrative/neuronet/mood/neuronet-mood.webp.png'),
  'neuronet.saga.ghost-protocol-banner': require('@/assets/images/narrative/neuronet/sagas/ghost-protocol-banner.webp.png'),
  'neuronet.chapter.ghost-protocol.01-signal-leak': require('@/assets/images/narrative/neuronet/chapters/ghost-protocol/01-signal-leak.webp.png'),
  'neuronet.chapter.ghost-protocol.02-blackline-drop': require('@/assets/images/narrative/neuronet/chapters/ghost-protocol/02-blackline-drop.webp.png'),
  'neuronet.chapter.ghost-protocol.03-memory-shard': require('@/assets/images/narrative/neuronet/chapters/ghost-protocol/03-memory-shard.webp.png'),
  'neuronet.chapter.ghost-protocol.04-ghost-sector': require('@/assets/images/narrative/neuronet/chapters/ghost-protocol/04-ghost-sector.webp.png'),
  'neuronet.chapter.ghost-protocol.05-cains-mirror': require('@/assets/images/narrative/neuronet/chapters/ghost-protocol/05-cains-mirror.webp.png'),
  'neuronet.character.lyra-voss-neutral': require('@/assets/images/narrative/neuronet/characters/lyra-voss-neutral.webp.png'),
  'neuronet.character.lyra-voss-approving': require('@/assets/images/narrative/neuronet/characters/lyra-voss-approving.png.png'),
  'neuronet.character.lyra-voss-worried': require('@/assets/images/narrative/neuronet/characters/lyra-voss-worried.png.png'),
  'neuronet.character.director-cain-neutral': require('@/assets/images/narrative/neuronet/characters/director-cain-neutral.png.png'),
  'neuronet.character.director-cain-taunting': require('@/assets/images/narrative/neuronet/characters/director-cain-taunting.webp.png'),
  'neuronet.character.director-cain-angry': require('@/assets/images/narrative/neuronet/characters/director-cain-angry.png.png'),
  'neuronet.reward.signal-carrier-badge': require('@/assets/images/narrative/neuronet/ui/ghost-protocol/reward-signal-carrier-badge.png.png'),
  'neuronet.reward.blackline-runner-title': require('@/assets/images/narrative/neuronet/ui/ghost-protocol/reward-blackline-runner-title.png.png'),
  'neuronet.reward.ghost-patch-cosmetic': require('@/assets/images/narrative/neuronet/ui/ghost-protocol/reward-ghost-patch-cosmetic.png.png'),
  'neuronet.reward.sector-phantom-badge': require('@/assets/images/narrative/neuronet/ui/ghost-protocol/reward-sector-phantom-badge.png.png'),
  'neuronet.reward.zenith-corporation-story-unlock': require('@/assets/images/narrative/neuronet/ui/ghost-protocol/reward-zenith-corporation-unlock.png.png'),
  'neuronet.saga.zenith-corporation-banner': require('@/assets/images/narrative/neuronet/sagas/zenith-corporation-banner.webp.png'),
  'neuronet.chapter.zenith-corporation.01-first-login': require('@/assets/images/narrative/neuronet/chapters/zenith-corporation/01-first-login.webp.png'),
  'neuronet.chapter.zenith-corporation.02-metrics-review': require('@/assets/images/narrative/neuronet/chapters/zenith-corporation/02-metrics-review.webp.png'),
  'neuronet.chapter.zenith-corporation.03-compliance-floor': require('@/assets/images/narrative/neuronet/chapters/zenith-corporation/03-compliance-floor.webp.png'),
  'neuronet.chapter.zenith-corporation.04-productivity-purge': require('@/assets/images/narrative/neuronet/chapters/zenith-corporation/04-productivity-purge.webp.png'),
  'neuronet.chapter.zenith-corporation.05-the-helix-report': require('@/assets/images/narrative/neuronet/chapters/zenith-corporation/05-the-helix-report.webp.png'),
  'neuronet.character.mira-kade-neutral': require('@/assets/images/narrative/neuronet/characters/mira-kade-neutral.webp.png'),
  'neuronet.character.mira-kade-approving': require('@/assets/images/narrative/neuronet/characters/mira-kade-approving.png.png'),
  'neuronet.character.mira-kade-worried': require('@/assets/images/narrative/neuronet/characters/mira-kade-worried.png.png'),
  'neuronet.character.executive-helix-neutral': require('@/assets/images/narrative/neuronet/characters/executive-helix-neutral.png.png'),
  'neuronet.character.executive-helix-taunting': require('@/assets/images/narrative/neuronet/characters/executive-helix-taunting.webp.png'),
  'neuronet.character.executive-helix-angry': require('@/assets/images/narrative/neuronet/characters/executive-helix-angry.png.png'),
  'neuronet.reward.first-login-badge': require('@/assets/images/narrative/neuronet/ui/zenith-corporation/reward-first-login-badge.png.png'),
  'neuronet.reward.metric-analyst-title': require('@/assets/images/narrative/neuronet/ui/zenith-corporation/reward-metric-analyst-title.png.png'),
  'neuronet.reward.chrome-access-card-cosmetic': require('@/assets/images/narrative/neuronet/ui/zenith-corporation/reward-chrome-access-card-cosmetic.png.png'),
  'neuronet.reward.compliance-breaker-badge': require('@/assets/images/narrative/neuronet/ui/zenith-corporation/reward-compliance-breaker-badge.png.png'),
  'neuronet.reward.neon-delivery-story-unlock': require('@/assets/images/narrative/neuronet/ui/zenith-corporation/reward-neon-delivery-story-unlock.png.png'),
  'neuronet.saga.neon-delivery-banner': require('@/assets/images/narrative/neuronet/sagas/neon-delivery-banner.webp.png'),
  'neuronet.chapter.neon-delivery.01-first-route': require('@/assets/images/narrative/neuronet/chapters/neon-delivery/01-first-route.webp.png'),
  'neuronet.chapter.neon-delivery.02-rainline-package': require('@/assets/images/narrative/neuronet/chapters/neon-delivery/02-rainline-package.webp.png'),
  'neuronet.chapter.neon-delivery.03-stolen-coordinates': require('@/assets/images/narrative/neuronet/chapters/neon-delivery/03-stolen-coordinates.webp.png'),
  'neuronet.chapter.neon-delivery.04-jackal-run': require('@/assets/images/narrative/neuronet/chapters/neon-delivery/04-jackal-run.webp.png'),
  'neuronet.chapter.neon-delivery.05-final-delivery': require('@/assets/images/narrative/neuronet/chapters/neon-delivery/05-final-delivery.webp.png'),
  'neuronet.character.juno-vale-neutral': require('@/assets/images/narrative/neuronet/characters/juno-vale-neutral.webp.png'),
  'neuronet.character.juno-vale-approving': require('@/assets/images/narrative/neuronet/characters/juno-vale-approving.png.png'),
  'neuronet.character.juno-vale-worried': require('@/assets/images/narrative/neuronet/characters/juno-vale-worried.png.png'),
  'neuronet.character.razor-jackal-neutral': require('@/assets/images/narrative/neuronet/characters/razor-jackal-neutral.png.png'),
  'neuronet.character.razor-jackal-taunting': require('@/assets/images/narrative/neuronet/characters/razor-jackal-taunting.webp.png'),
  'neuronet.character.razor-jackal-angry': require('@/assets/images/narrative/neuronet/characters/razor-jackal-angry.png.png'),
  'neuronet.reward.first-route-cleared-badge': require('@/assets/images/narrative/neuronet/ui/neon-delivery/reward-first-route-cleared-badge.png.png'),
  'neuronet.reward.rainline-courier-title': require('@/assets/images/narrative/neuronet/ui/neon-delivery/reward-rainline-courier-title.png.png'),
  'neuronet.reward.neon-rider-patch-cosmetic': require('@/assets/images/narrative/neuronet/ui/neon-delivery/reward-neon-rider-patch-cosmetic.png.png'),
  'neuronet.reward.jackal-survivor-badge': require('@/assets/images/narrative/neuronet/ui/neon-delivery/reward-jackal-survivor-badge.png.png'),
  'neuronet.reward.final-runner-title': require('@/assets/images/narrative/neuronet/ui/neon-delivery/reward-final-runner-title.png.png'),
};
